// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'App-logo-spin': string;
  container: string;
  header: string;
  intro: string;
  logo: string;
}
declare var cssExports: CssExports;
export = cssExports;
