// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'thumbs-down-button': string;
  'thumbs-up-button': string;
  'title': string;
}
declare var cssExports: CssExports;
export = cssExports;
