// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bit-tag-pills': string;
  'dropdown-caret-margin': string;
  'dropdown-option': string;
  'filter-pill': string;
  'thumbs-down-button': string;
  'thumbs-up-button': string;
}
declare var cssExports: CssExports;
export = cssExports;
