branches:
  only:
  - master
os:
  - linux
  - osx
  - windows
language: node_js
node_js:
  - 'lts/*'
services:
  - xvfb
before_script:
install:
  - cd client; npm install; cd -
  - cd server; npm install; cd -
script:
  - ./server/node_modules/.bin/eslint 'server/**/*.{js,ts,tsx}'
  - ./client/node_modules/.bin/eslint 'client/**/*.{js,ts,tsx}'
  - npm run build --prefix=client
  - if [ "$TRAVIS_OS_NAME" != "windows" ]; then npm run test:all --prefix=server ; fi
  - if [ "$TRAVIS_OS_NAME" != "windows" ]; then npm run test --prefix=client ; fi
