import * as query from './query_params';

export const FILTER_CHAR_LUIGI = 'Luigi';
export const FILTER_CHAR_MARIO = 'Mario';
export const FILTER_CHAR_DK = 'Donkey Kong';
export const FILTER_CHAR_LINK = 'Link';
export const FILTER_CHAR_SAMUS = 'Samus';
export const FILTER_CHAR_FALCON = 'Captain Falcon';
export const FILTER_CHAR_NESS = 'Ness';
export const FILTER_CHAR_YOSHI = 'Yoshi';
export const FILTER_CHAR_KIRBY = 'Kirby';
export const FILTER_CHAR_FOX = 'Fox';
export const FILTER_CHAR_PIKA = 'Pikachu';
export const FILTER_CHAR_JIGGLY = 'Jigglypuff';

export const FILTER_STAGE_PEACH = 'Peach\'s Castle';
export const FILTER_STAGE_CONGO = 'Congo Jungle';
export const FILTER_STAGE_HYRULE = 'Hyrule Castle';
export const FILTER_STAGE_ZEBES = 'Planet Zebes';
export const FILTER_STAGE_MUSHROOM = 'Mushroom Kingdom';
export const FILTER_STAGE_DREAMLAND = 'Dream Land';
export const FILTER_STAGE_SECTOR_Z = 'Sector Z';
export const FILTER_STAGE_SAFFRON = 'Saffron City';
export const FILTER_STAGE_META_CRYSTAL = 'Meta Crystal (19xx)';
export const FILTER_STAGE_YOSHI_ISLAND_19XX = 'Yoshi\'s Island (19xx)';
export const FILTER_STAGE_FINAL_DESTINATION = 'Final Destination (19xx)';
export const FILTER_STAGE_BATTLEFIELD = 'Battlefield (19xx)';

export const FILTER_TAG_APPROACH = 'Approach';
export const FILTER_TAG_EDGEGUARDING = 'Edgeguarding';
export const FILTER_TAG_COMBOS = 'Combos';
export const FILTER_TAG_ESCAPES = 'Escapes';

export const PARAMS_TO_DISPLAY_CHARS: { [key: string]: string } = {
  [query.FILTER_PARAM_LUIGI]: FILTER_CHAR_LUIGI,
  [query.FILTER_PARAM_MARIO]: FILTER_CHAR_MARIO,
  [query.FILTER_PARAM_DK]: FILTER_CHAR_DK,
  [query.FILTER_PARAM_LINK]: FILTER_CHAR_LINK,
  [query.FILTER_PARAM_SAMUS]: FILTER_CHAR_SAMUS,
  [query.FILTER_PARAM_FALCON]: FILTER_CHAR_FALCON,
  [query.FILTER_PARAM_NESS]: FILTER_CHAR_NESS,
  [query.FILTER_PARAM_YOSHI]: FILTER_CHAR_YOSHI,
  [query.FILTER_PARAM_KIRBY]: FILTER_CHAR_KIRBY,
  [query.FILTER_PARAM_FOX]: FILTER_CHAR_FOX,
  [query.FILTER_PARAM_PIKA]: FILTER_CHAR_PIKA,
  [query.FILTER_PARAM_JIGGLY]: FILTER_CHAR_JIGGLY,
};

export const DISPLAY_TO_PARAMS_CHARS: { [key: string]: string } = {
  [FILTER_CHAR_LUIGI]: query.FILTER_PARAM_LUIGI,
  [FILTER_CHAR_MARIO]: query.FILTER_PARAM_MARIO,
  [FILTER_CHAR_DK]: query.FILTER_PARAM_DK,
  [FILTER_CHAR_LINK]: query.FILTER_PARAM_LINK,
  [FILTER_CHAR_SAMUS]: query.FILTER_PARAM_SAMUS,
  [FILTER_CHAR_FALCON]: query.FILTER_PARAM_FALCON,
  [FILTER_CHAR_NESS]: query.FILTER_PARAM_NESS,
  [FILTER_CHAR_YOSHI]: query.FILTER_PARAM_YOSHI,
  [FILTER_CHAR_KIRBY]: query.FILTER_PARAM_KIRBY,
  [FILTER_CHAR_FOX]: query.FILTER_PARAM_FOX,
  [FILTER_CHAR_PIKA]: query.FILTER_PARAM_PIKA,
  [FILTER_CHAR_JIGGLY]: query.FILTER_PARAM_JIGGLY,
};

export const PARAMS_TO_DISPLAY_STAGES: { [key: string]: string } = {
  [query.FILTER_PARAM_PEACH]: FILTER_STAGE_PEACH,
  [query.FILTER_PARAM_CONGO]: FILTER_STAGE_CONGO,
  [query.FILTER_PARAM_HYRULE]: FILTER_STAGE_HYRULE,
  [query.FILTER_PARAM_ZEBES]: FILTER_STAGE_ZEBES,
  [query.FILTER_PARAM_MUSHROOM]: FILTER_STAGE_MUSHROOM,
  [query.FILTER_PARAM_DREAMLAND]: FILTER_STAGE_DREAMLAND,
  [query.FILTER_PARAM_SECTOR_Z]: FILTER_STAGE_SECTOR_Z,
  [query.FILTER_PARAM_SAFFRON]: FILTER_STAGE_SAFFRON,
  [query.FILTER_PARAM_META_CRYSTAL]: FILTER_STAGE_META_CRYSTAL,
  [query.FILTER_PARAM_YOSHI_ISLAND_19XX]: FILTER_STAGE_YOSHI_ISLAND_19XX,
  [query.FILTER_PARAM_FINAL_DESTINATION]: FILTER_STAGE_FINAL_DESTINATION,
  [query.FILTER_PARAM_BATTLEFIELD]: FILTER_STAGE_BATTLEFIELD,
};

export const DISPLAY_TO_PARAMS_STAGES: { [key: string]: string } = {
  [FILTER_STAGE_PEACH]: query.FILTER_PARAM_PEACH,
  [FILTER_STAGE_CONGO]: query.FILTER_PARAM_CONGO,
  [FILTER_STAGE_HYRULE]: query.FILTER_PARAM_HYRULE,
  [FILTER_STAGE_ZEBES]: query.FILTER_PARAM_ZEBES,
  [FILTER_STAGE_MUSHROOM]: query.FILTER_PARAM_MUSHROOM,
  [FILTER_STAGE_DREAMLAND]: query.FILTER_PARAM_DREAMLAND,
  [FILTER_STAGE_SECTOR_Z]: query.FILTER_PARAM_SECTOR_Z,
  [FILTER_STAGE_SAFFRON]: query.FILTER_PARAM_SAFFRON,
  [FILTER_STAGE_META_CRYSTAL]: query.FILTER_PARAM_META_CRYSTAL,
  [FILTER_STAGE_YOSHI_ISLAND_19XX]: query.FILTER_PARAM_YOSHI_ISLAND_19XX,
  [FILTER_STAGE_FINAL_DESTINATION]: query.FILTER_PARAM_FINAL_DESTINATION,
  [FILTER_STAGE_BATTLEFIELD]: query.FILTER_PARAM_BATTLEFIELD,
};

export const PARAMS_TO_DISPLAY_TAGS: { [key: string]: string } = {
  [query.FILTER_PARAM_APPROACH]: FILTER_TAG_APPROACH,
  [query.FILTER_PARAM_EDGEGUARDING]: FILTER_TAG_EDGEGUARDING,
  [query.FILTER_PARAM_COMBOS]: FILTER_TAG_COMBOS,
  [query.FILTER_PARAM_ESCAPES]: FILTER_TAG_ESCAPES,
};

export const DISPLAY_TO_PARAMS_TAGS: { [key: string]: string } = {
  [FILTER_TAG_APPROACH]: query.FILTER_PARAM_APPROACH,
  [FILTER_TAG_EDGEGUARDING]: query.FILTER_PARAM_EDGEGUARDING,
  [FILTER_TAG_COMBOS]: query.FILTER_PARAM_COMBOS,
  [FILTER_TAG_ESCAPES]: query.FILTER_PARAM_ESCAPES,
};
